name: Deploy BigCommerce Theme

on:
  push:
    branches:
      - master  # Deploy only when changes are pushed to the main branch

jobs:
  deploy-theme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure compatibility with Stencil CLI

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm install

      # Install Stencil CLI globally
      - name: Install Stencil CLI
        run: npm install -g @bigcommerce/stencil-cli

         # Initialize Stencil Configuration
      - name: Initialize Stencil
        run: |
          stencil init -u $STORE_URL -t $STORE_TOKEN -h https://api.bigcommerce.com
        env:
          STORE_URL: ${{ secrets.BC_STORE_URL }}
          STORE_TOKEN: ${{ secrets.BC_ACCESS_TOKEN }}
          STORE_HASH: ${{ secrets.BC_STORE_HASH }}

      # Validate the theme
      - name: Validate Theme
        run: stencil bundle

      # Deploy the theme
      - name: Deploy Theme
        run: stencil push -a Light -c 1
        env:
          STORE_URL: ${{ secrets.BC_STORE_URL }}
          STORE_TOKEN: ${{ secrets.BC_ACCESS_TOKEN }}
          STORE_HASH: ${{ secrets.BC_STORE_HASH }}
